builder/urls.py
from django.urls import path
from . import views

app_name = 'builder'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('cv/', views.download, name='download')
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('builder.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

builder/models.py
from django.db import models

# Create your models here.

builder/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
#from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import default_url_fetcher, HTML, CSS
import logging
from base64 import b64encode
# import cairosvg
from xml import etree  # refer to xml.etree.ElementTree documentions

logger = logging.getLogger('weasyprint')

def my_fetcher(url): # external urls
    if url.startswith('assets://'):
        pass
        #url = url[len('assets://'):]
        #url = "file://" + safe_join(settings.ASSETS_ROOT, url) # example : file:///C:/Users/a/Projects/my-projects/cv_builder/static/img/eisa-91.jpg
    return default_url_fetcher(url)


#def svg_embed(html):
#    """For the child of nvd3 nodes (svg) munge them into b64encoded data
#    as a workaround for https://github.com/Kozea/WeasyPrint/issues/75"""
#    root = html.root_element
#    svgs = root.findall('.//nvd3')
#    for svg in svgs:
#        child = svg.getchildren()[0]
#        encoded = b64encode(etree.tostring(child)).decode()
#        encoded_data = "data:image/svg+xml;charset=utf-8;base64," + encoded
#        encoded_child = etree.fromstring('<img src="%s"/>' % encoded_data)
#        svg.replace(child, encoded_child)
#    return html
# and after use as svg_embed(HTML(string=html, base_url=base_url)).write_pdf..


def home_page_view(request):
    # cairosvg.svg2png(url="/code/static/assets/mail.svg", write_to="/code/static/img/output.png")   # convert svg to png
    return render(request, './builder/home.html')


def download(request):
    print('downloading..')
    logger.addHandler(logging.FileHandler('/code/logs/weasyprint.log'))
    html = render_to_string('builder/cv.html')
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=Eisa-Nahardani.pdf'
    HTML(string=html, base_url=request.build_absolute_uri(), url_fetcher=my_fetcher ).write_pdf(response)
    return response

templates/base.html
<!--
=========================================================
* Eisa Nahardani -- Web Developer -- 92developer92@gmail.com
======================================================
-->
{% load static  %}
<!DOCTYPE html>
<html lang="en" class="notranslate" translate="no">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->

<title>
  {% block title %}{% endblock %}
</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="">
<meta name="author" content="Eisa Nahardani">


<!-- bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static 'css/core/bootstrap.min.css' %}">

<!-- FA Icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
       crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<!-- MY CSS -->
<link rel="stylesheet" href="{% static '/css/base.css' %}">

{% block css %}
{% endblock css %}
</head>

<body>

    {% block content %}
    {% endblock content %}


    {% include './scripts.html' %}

    {% block js %}
    {% endblock js %}
</body>

</html>

templates/builder/cv-sample.html
{% load static %}

<div class="half-circle">
</div>

<div class="note">
<span class="line-one">Note</span> This resume is generated by Django framework<br>
  you can check my libraries in github
</div>

<div class="row wrapper-image">
  <img src="{% static 'img/eisa-91.jpg' %}" alt="" class="img">
</div>


<div class="bio">
  <span class="full-name">Eisa Nahardani</span>
  <span class="job-one">Senior Web Developer</span>
  <span class="job-two">Junior Android Developer</span>
</div>


<div class="heading">
  Skills
</div>
<div class="skills">
  <span>Docker</span>
  <span>Git</span>
  <span>Celery</span>
  <span>Django</span>
  <span>Redis</span>
  <span>PostgreSQL</span>
  <span>JQuery</span>
  <span>CSS</span>
  <span>HTML</span>
  <span>Javascript</span>
  <span>CI/CD</span>
  <span>MemCached</span>
  <span>Python</span>
  <span>Nginx</span>
  <span>RabbitMQ</span>
</div>

templates/builder/cv.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/builder/cv.css' %}">
{% endblock css %}

{% block content %}
  {% include 'builder/cv-sample.html' %}
{% endblock %}

templates/builder/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/builder/cv.css' %}">
{% endblock css %}

{% block content %}
  {% include 'builder/cv-sample.html' %}
  <a href="{% url 'builder:download' %}" >Download CV</a>
{% endblock %}

templates/scripts.html
{% load static %}
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" ></script>
<script src="{% static 'js/core/popper.min.js' %}" ></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" defer></script>

<!-- my js files  --->
<script src="{% static 'js/base.js' %}" defer></script>